feat: add support for range validation
billysbilling/ember-date-field pull request #3
Opened 2018-11-19 09:27 UTC by razvanz

2018-11-19 09:48 UTC, fiolkaf requested changes

2018-11-19 09:48 UTC, fiolkaf commented on src/js/date-field.js
> +    init: function() {
init is already defined: https://github.com/billysbilling/ember-date-field/pull/3/files#diff-758f4c4248fb7fd991a7c5e3bf077f42R33

Do we really want to support dates s numbers?

2020-12-09 13:27 UTC, fandridis commented
Should we change it to look to `develop` branch first?

2020-12-09 13:29 UTC, razvanz commented
There's no develop branch in this repo

2020-12-09 13:34 UTC, fandridis approved these changes
Looks like a good addition to have. 👍

2020-12-09 13:34 UTC, merged